exec-once = hypridle
exec-once = hyprpaper
exec-once = swaync # Notifications
exec-once = udiskie # Manage removable media like flash drives
exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar

