input {
    kb_layout = de
    kb_variant = neo_qwertz
    kb_model =
    kb_options =
    kb_rules =

    repeat_rate = 35
    repeat_delay = 200

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
	    disable_while_typing = false
    }
}

cursor {
    inactive_timeout = 30
    no_hardware_cursors = true
}

gesture = 3, horizontal, workspace
