# Ignore maximize requests from apps.
windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}


# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}


# Rules
windowrule {
  name = windowrule-3
  float = on
  pin = on
  match:class = ^(firefox)$
  match:title = ^(Picture-in-Picture)$
}

windowrule {
  name = windowrule-4
  fullscreen = on
  match:class = ^(org.gnome.Loupe)$
}


windowrule {
  name = windowrule-5
  opacity = 0.85 0.85
  match:class = ^(kitty)$
}


# XWayland video bridge
windowrule {
  name = windowrule-6
  opacity = 0.0 override
  no_anim = on
  no_initial_focus = on
  max_size = 1 1
  no_blur = on
  no_focus = on
  match:class = ^(xwaylandvideobridge)$
}

